/*
 * This file is part of GenoViewer.
 *
 * GenoViewer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GenoViewer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GenoViewer.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClosableTabbedPane.java
 *
 * Created on 2010.06.29., 12:11:49
 */
package hu.astrid.viewer.gui;

import java.awt.Dimension;
import javax.swing.JTabbedPane;

/**
 *
 * @author OTTO
 */
public class ClosableTab extends javax.swing.JPanel {

	private JTabbedPane tabbedPane;

	/** Creates new form ClosableTabbedPane */
	public ClosableTab(JTabbedPane tabbedPane) {
		this.tabbedPane = tabbedPane;
		initComponents();
		setOpaque(false);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hideTabbedPane = new javax.swing.JButton();
        tabLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        hideTabbedPane.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hu/astrid/viewer/gui/closeIcon.png"))); // NOI18N
        hideTabbedPane.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hideTabbedPane.setBorderPainted(false);
        hideTabbedPane.setContentAreaFilled(false);
        hideTabbedPane.setFocusable(false);
        hideTabbedPane.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hideTabbedPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hideTabbedPaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hideTabbedPaneMouseExited(evt);
            }
        });
        hideTabbedPane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideTabbedPaneActionPerformed(evt);
            }
        });

        tabLabel.setText("valami");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hideTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
            .addComponent(hideTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tabLabel.setText(tabbedPane.getTitleAt(0));
    }// </editor-fold>//GEN-END:initComponents

	private void hideTabbedPaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideTabbedPaneActionPerformed
		tabbedPane.setVisible(false);
	}//GEN-LAST:event_hideTabbedPaneActionPerformed

	private void hideTabbedPaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideTabbedPaneMouseEntered
		hideTabbedPane.setBorderPainted(true);
	}//GEN-LAST:event_hideTabbedPaneMouseEntered

	private void hideTabbedPaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideTabbedPaneMouseExited
		hideTabbedPane.setBorderPainted(false);
	}//GEN-LAST:event_hideTabbedPaneMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hideTabbedPane;
    private javax.swing.JLabel tabLabel;
    // End of variables declaration//GEN-END:variables
}
